specs/tldr-lint-helper.js

It worked everywhere but in NodeJS 0.10.
Later we can rewrite with Babel.

NodeJS 0.10 support. Use old for instead of for-of operator

---

tldr.l

This may happen when the first word starts with the letter that identifies the option.
C.f. https://github.com/tldr-pages/tldr/pull/1030 and https://github.com/tldr-pages/tldr/pull/1018

Allow example descriptions to start with `[`

---

lib/tldr-lint.js

[This](https://github.com/tldr-pages/tldr/pull/1094) pull request on tldr had a failing lint test because of trailing white space, but the error message only specified that the description must end with a colon. 
This pull request clarifies what the lint is really checking for.

Clarify wording in error messages esp. TLDR005

---

.gitignore
package.json

This PR stops the `package-lock.json` being tracked in Git to prevent accidental commits.
It also adds a `files` key to the `package.json` which makes it easier to manage the files that should be included in the release (`package.json`, `LICENSE.md`, and `README.md` are all included by default). 👍🏻

chore: prepare package for npm release

---

package.json

I think we can leave the Grunt package versions for now, as it's probably worth moving away from Grunt in future. 👍🏻

chore(npm): bump dependencies to latest versions

---

README.md
lib/tldr-lint.js
lib/tldr-parser.js
specs/pages/016.md
specs/pages/017.md
specs/tldr-lint.spec.js
tldr.l
tldr.yy

Expected format is as follows:
```
> More information: <http://some.site.invalid/>.
```
---
I missed the correct format when writing tldr pages and was surprised that the linter showed no warnings. Here's an implementation.

Parse and lint the homepage line

---

.github/dependabot.yml

Our dependencies are way behind, so I feel like it might be best to sort this before adding Dependabot. 🤔
I think for now we probably only really need to update `commander` and `jison`. And then in future we can move away from Grunt to npm scripts. 👍🏻

ci(dependabot): add Dependabot for version updates

---

.github/workflows/test.yml

This updates to force colour output in the test step, which makes the CI output much easier to read.

ci: update tests to always use colour output

---

README.md
lib/tldr-lint.js
specs/pages/019.md
specs/tldr-lint.spec.js

I'm not entirely sure about this as I couldn't actually add it into the lexer files, so I've added it into the actual JS.
This looks a little bit odd, but seems to work like all the others. 👍🏻
https://github.com/owenvoke/tldr-lint/blob/0992dd3e5ba3b51f1252666e90516ce931ee8176/lib/tldr-lint.js#L175

feat: add check for max of 8 examples

---

README.md

I just created #25 and #26 to track the TODO entries that were still in the README. The other items from the [original list](https://github.com/tldr-pages/tldr-lint/commit/e2b5156b9c1055019109736f653958e5f29952a4) have been removed as they were implemented.

README: remove TODOs now tracked as issues

---

.github/workflows/test.yml

Node v13 is EOL'd since June 2020, and v15 is the current version now (since October 2020). This change keeps tests running only in the supported Node versions (LTS), and the current one.

Update Node versions in test suite

---

specs/pages/examples.md
specs/tldr-lint.spec.js

The deprecated/skipped test of `Multiple example lines` is the inverse of the test of `TLDR105` which ensures no multiple lines per example. Given that the lint rule has been in place for 5+ years and would seem unlikely to be removed, probably safe to remove this skipped test.
Both `specs/pages/examples.md` and `specs/pages/105.md` are mostly the same with the only difference being that `examples.md` has the last word of the second line wrapped as a token (`{{this}}`) while `105.md` does not. Not sure that's a meaningful difference as it does not trigger an error or anything.

remove skipped test, duplicate of TLDR105

---

lib/tldr-lint.js
lib/tldr-parser.js
specs/pages/014.md
specs/tldr-lint.spec.js
tldr.l

`TLDR014` states that "Page should contain no trailing whitespace", however this was not validated for the title block or the information link lines. 
Adding this rule causes the following pages to error, with included PR resolving the lint:
* [pages/linux/flameshot.md](https://github.com/tldr-pages/tldr/blob/b5a3c99e17fb4ac281f0b15b8757e2ea2a6bba5b/pages/linux/flameshot.md) (https://github.com/tldr-pages/tldr/pull/5068)
* [pages/common/uvicorn.md](https://github.com/tldr-pages/tldr/blob/22577ba81099330d55a19d207d2097d6fa778c06/pages/common/uvicorn.md) (https://github.com/tldr-pages/tldr/pull/5069)

fix: catch trailing spaces in title and information_link lines

---

lib/tldr-parser.js
specs/pages/title++.md
specs/tldr-lint.spec.js
tldr.l

This PR allows for page titles to have the `+` symbol in them. This is nominally to fix the lint failure in tldr-pages/tldr#5088, where I could not rename the page title to be `g++` to match its filename.

fix: allow page titles with + symbol

---

README.md
lib/tldr-lint-cli.js
lib/tldr-lint.js
specs/pages/107
specs/tldr-lint-helper.js
specs/tldr-lint.spec.js

This splits apart #32 to only include the lint check for the md file extension. Hopefully this part of it is not contentious and can be merged.
Closes #25

feat: add lint check for .md file extension

---

README.md
lib/tldr-lint.js
specs/pages/109A.md
specs/tldr-lint.spec.js

With this change, the following pages are showing as needing to be changed (in the main English versions):
```
pages/common/R.md:0: TLDR109 File name should be lowercase
pages/common/theHarvester.md:0: TLDR109 File name should be lowercase
pages/linux/eyeD3.md:0: TLDR109 File name should be lowercase
pages/osx/GetFileInfo.md:0: TLDR109 File name should be lowercase
pages/osx/csshX.md:0: TLDR109 File name should be lowercase
```
Closes https://github.com/tldr-pages/tldr/issues/5085 (kind of...)

feat: add lint check for lowercase filename

---

lib/tldr-parser.js
tldr.l

In https://github.com/tldr-pages/tldr/pull/5205, a new page for `[` is being added. tldr-lint doesn't like that very much, so this (should) fix the issue.

allow [ character in title

---

.gitattributes

Many good reasons, for one, so that developers can work on tldr-lint on Macs.

chore: correct line endings in .gitattributes for specs/pages/failing/010.md

---

lib/tldr-parser.js
tldr.yy

I didn't touch the test pages because some of them have trailing whitespace intentionally to test the linter.﻿

Cleanup trailing whitespace

---

package.json

To omit specs/ and other development files from the built tarball published
to npm

Remove useless 'files' entries from package.json

---

jasmine.json
package.json
specs/.eslintrc.json
specs/tldr-lint-helper.js
specs/tldr-lint.spec.js

The specs directory was not being linted, This was causing my editor to be upset when I opened a test file. This PR changes it so that it will be.
Beyond the lint changes, the most significant change is removing the `specs/tldr-lint-helper.js` file from jasmine helper to being just a regularly imported module. It's not super well documented, but the `helpers` of jasmine is aimed at allowing developers to augment the built-in jasmine behavior or run `beforeEach` methods for test suite or whatever, not really setting custom util functions. You can use it for that, but then it requires specifying that each is a global variable for eslint to work and also abusing JS hoisting to even function (e.g. you have to write `lintFile = function(file)`, writing `var lintFile = function(file)` will …

run eslint over specs directory

---

lib/tldr-lint.js

Closes #57
Old output:
```text
$ node lib/tldr-lint-cli.js ../tldr/pages/common/aapt.md
Error: Parse error on line 5:
-------^
Expecting 'TEXT', 'DASH', 'BACKTICK', got 'GREATER_THAN'
```
New output:
```text
$ node lib/tldr-lint-cli.js ../tldr/pages/common/aapt.md
../tldr/pages/common/aapt.md:
Error: Parse error on line 5:
-------^
Expecting 'TEXT', 'DASH', 'BACKTICK', got 'GREATER_THAN'
```

Print out filename above parse errors

---

lib/tldr-lint-cli.js

Upgrading to commander 7 (6a2adb2a4bfc07c2f4a24d0340fe76089bc27c31) had a couple of breaking changes with how commander is used, and the args and options referenced. This meant that trying to pass in the `--verbose` flag was broken for example. This PR updates the codebase so that it utilizes the new commander output structure.
Given that the parameter passed to `cli.process` different due to breaking change when going to commander 7, I decided to then modify the parameter list to have it be a bit more straight forward such that it no longer relies on commander per-se, but rather just accepts a string filename and a key/value object of arguments.

fix passing options to cli

---

package-lock.json
package.json

This moves husky to be run as the recommended `prepare` run-script instead of `postinstall` and `prepublish` stuff it did have. This has the advantage that prepare will run only on installing and publishing in the local directory, and not affect any downstream installations of the linter, rendering the `pinst` devDependency redundant and unnecessary.

move husky to prepare run-script

---

lib/tldr-lint-cli.js
lib/tldr-lint.js
specs/tldr-lint-helper.js
specs/tldr-lint.spec.js

This adds a new flag to allow ignoring specific TLDR errors (comma separated). The purpose here is to then hook up tldr-lint to run on all incoming pages (not just english) and comment as appropriate, ignoring the rules that are english only.

add flag to ignore specific errors

---

CHANGELOG.md
package-lock.json
package.json

Bumping the version of tldr-lint here as I'd like to incorporate the changes here into the general tldr repo, especially running most of tldr-lint over all non-english pages with the exception of a handful of the rules that are English oriented (e.g. TLDR104).
I think that this could be merged after #60 which is ready sans test case, as not sure there's any user facing changes in the immediate works that would want to be included into this release.

chore: release v0.0.11

---

lib/tldr-parser.js
specs/pages/passing/special-characters.md
specs/tldr-lint.spec.js
tldr.l

Many latin language (in my case french) have an issue with the rule `TLDR015` => `Example descriptions should start with a capital letter`
If i want to start my sentence with a `È` it's not possible because the actual regex is => `/^[A-Z[]/`
Using this regex `/^[\p{Lu}\[]/u` instead do the trick
I also added a unit test for this case :)

chore: allow special uppercased characters

---

.github/workflows/test.yml

Node 15.x is EOL, and the 17.x release line is the current non-LTS supported version.

Replace testing on 15.x with 17.x

---

jasmine.json
package-lock.json
package.json
specs/.eslintrc.json

@MasterOdin mentioned this on https://github.com/tldr-pages/tldr-lint/pull/127#issuecomment-1006778671, Jest appears to work as a drop-in replacement for Jasmine. The only issue I had was this notice, but not sure about it...
https://github.com/owenvoke/tldr-lint/runs/4737636053?check_suite_focus=true#step:7:10
Looks like this is related to the trailing comma in [the test page for TLDR004](specs/pages/failing/004.md). I think this should be changed probably...

tests: replace Jasmine with Jest

---

.gitattributes
.github/workflows/test.yml

ci: add Windows testing to CI

---

.eslintrc.json
lib/tldr-lint-cli.js
lib/tldr-lint.js
specs/tldr-lint-helper.js
specs/tldr-lint.spec.js

PR replaces all usages of `var` in the codebase with `const` or `let` as appropriate. No reason to not start looking to modernize the codebase a bit given we have no obligation to support ancient versions of Node that don't support `let` or `const`.

Replace usage of var with const/let

---

README.md

PR removes the david-dm badge from the README as the service has been down since at least January and there's no word from the maintainer if or when it could possibly return. With dependabot also making PRs for any out of date dependency, we also shouldn't have any out of date deps anyway.

Remove defunct david-dm badge from README

---

.github/workflows/test.yml
package.json

PR drops support for node 12 as it's reached end of life and is no longer supported. I've also replace node 17 with node 18 in the test matrix as the former is also end of life and the latter is the upcoming LTS release so we should verify it works. However, since we're not making any changes to explicitly support node 18 and that node 17 isn't LTS, I don't think we need to call this change out in a separate commit.

Set node 14 as minimum supported version

---

README.md
lib/tldr-lint-cli.js

So it doesn't clash with the short version of `--in-place`.
And updated readme to include this and other missed options.

fix: change short version of --ignore from -i to -I

---

README.md
lib/tldr-lint.js
lib/tldr-parser.js
specs/pages/failing/020.md
specs/pages/passing/descriptions.md
specs/tldr-lint.spec.js
tldr.l

closes #298
The linter now rejects "NOTE:" and "note" in the page description and example descriptions.
It does not reject other misspellings like "NoTe:", because 1) I doubt anyone would make such misspellings without actively trying to be disruptive 2) those are easily caught by human reviewers.
Again, I added a unit test and ran the new linter against the entire database.

feat: add tldr 020: spelling of "Note: "

---

.github/workflows/publish.yml

This PR adds support for generating package provenance on publishing a release. Check out  https://docs.npmjs.com/generating-provenance-statements for more information.

feat/ci: add support for package provenance on publish

---

Dockerfile

https://docs.docker.com/go/dockerfile/rule/legacy-key-value-format/

fix: annotation warnings for "LegacyKeyValueFormat" in Dockerfile
